export const lineChartData = {
    labels: [
        'Patins',
        'Crosses',
        'Casques',
        'Protections',
        'Gants',
        'Maillots',
    ],
    datasets: [
        {
            label: "Ventes par catégorie (€)",
            data: [
                299.99 + 349.99,
                189.99 + 209.99,
                159.99,
                0,
                0,
                79.99,
            ],
            backgroundColor: [
                "rgba(255, 99, 132, 0.6)",
                "rgba(54, 162, 235, 0.6)",
                "rgba(255, 206, 86, 0.6)",
                "rgba(75, 192, 192, 0.6)",
                "rgba(153, 102, 255, 0.6)",
                "rgba(255, 159, 64, 0.6)",
            ],
            borderColor: [
                "rgba(255, 99, 132, 1)",
                "rgba(54, 162, 235, 1)",
                "rgba(255, 206, 86, 1)",
                "rgba(75, 192, 192, 1)",
                "rgba(153, 102, 255, 1)",
                "rgba(255, 159, 64, 1)",

            ],
            borderWidth: 1,
        },
    ],
}

export const barChartData = {
    labels: [
        'Patins',
        'Crosses',
        'Casques',
        'Protections',
        'Gants',
        'Maillots',
    ],
    datasets: [
        {
            label: "Ventes par catégorie (€)",
            data: [
                299.99 + 349.99,
                189.99 + 209.99,
                159.99,
                0,
                0,
                79.99,
            ],
            backgroundColor: [
                "rgba(255, 99, 132, 0.6)",
                "rgba(54, 162, 235, 0.6)",
                "rgba(255, 206, 86, 0.6)",
                "rgba(75, 192, 192, 0.6)",
                "rgba(153, 102, 255, 0.6)",
                "rgba(255, 159, 64, 0.6)",
            ],
            borderColor: [
                "rgba(255, 99, 132, 1)",
                "rgba(54, 162, 235, 1)",
                "rgba(255, 206, 86, 1)",
                "rgba(75, 192, 192, 1)",
                "rgba(153, 102, 255, 1)",
                "rgba(255, 159, 64, 1)",

            ],
            borderWidth: 1,
        },
    ],
};


export const pieChartData = {
    labels: [
        'Patins',
        'Crosses',
        'Casques',
        'Protections',
        'Gants',
        'Maillots',
    ],
    datasets: [
        {
            label: "Ventes par catégorie (€)",
            data: [
                299.99 + 349.99,
                189.99 + 209.99,
                159.99,
                0,
                0,
                79.99,
            ],
            backgroundColor: [
                "rgba(255, 99, 132, 0.6)",
                "rgba(54, 162, 235, 0.6)",
                "rgba(255, 206, 86, 0.6)",
                "rgba(75, 192, 192, 0.6)",
                "rgba(153, 102, 255, 0.6)",
                "rgba(255, 159, 64, 0.6)",
            ],
            borderColor: [
                "rgba(255, 99, 132, 1)",
                "rgba(54, 162, 235, 1)",
                "rgba(255, 206, 86, 1)",
                "rgba(75, 192, 192, 1)",
                "rgba(153, 102, 255, 1)",
                "rgba(255, 159, 64, 1)",

            ],
            borderWidth: 1,
        },
    ],
};